# Generated by Django 4.2.21 on 2025-05-31 13:30

import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('materials_json', models.JSONField(blank=True, null=True)),
                ('questions_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('baseline_understanding_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('traits_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['student_id'], name='agents_stud_student_dcbbd0_idx'), django.contrib.postgres.indexes.GinIndex(fields=['traits_json'], name='agents_stud_traits__d707b0_gin')],
            },
        ),
        migrations.CreateModel(
            name='SimAttempt',
            fields=[
                ('attempt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_label', models.CharField(max_length=100)),
                ('comprehension_json', models.JSONField()),
                ('answers_json', models.JSONField()),
                ('total_score', models.SmallIntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_id'], name='agents_quiz_quiz_id_f7ca57_idx'),
        ),
        migrations.AddIndex(
            model_name='simattempt',
            index=models.Index(fields=['attempt_id'], name='agents_sima_attempt_6fbfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='simattempt',
            index=models.Index(fields=['student'], name='agents_sima_student_8ffb77_idx'),
        ),
        migrations.AddIndex(
            model_name='simattempt',
            index=models.Index(fields=['quiz'], name='agents_sima_quiz_id_dcf31e_idx'),
        ),
    ]
